[build]
  # Directorio donde est치n tus archivos de frontend (HTML, CSS, JS)
  publish = "public"
  # Directorio donde Netlify encontrar치 las funciones del backend
  functions = "netlify/functions"

[[redirects]]
  # Esto redirige cualquier llamada a /api/* hacia nuestras funciones de Netlify.
  # Por ejemplo, una llamada a /api/login ejecutar치 la funci칩n login.js.
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200